<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Modules\Access\Support\RoutePermissions;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;

/**
 * Writes the canonical permission lists (spec §12.4) from the registered
 * landlord.admin and tenant.admin routes. The architecture tests assert the
 * committed files equal what this command would write.
 */
#[Signature('permissions:generate')]
#[Description('Generate config/permissions/generated/{landlord,tenant}.php from the admin routes')]
final class GeneratePermissions extends Command
{
    public function handle(RoutePermissions $routes): int
    {
        foreach (['landlord', 'tenant'] as $context) {
            $names = $routes->derive($context);

            $body = implode("\n", array_map(static fn (string $name): string => "    '{$name}',", $names));

            file_put_contents(config_path("permissions/generated/{$context}.php"), <<<PHP
                <?php

                declare(strict_types=1);

                // Generated by `php artisan permissions:generate` (spec §12.4). Do not edit by hand.

                return [
                {$body}
                ];

                PHP);

            $this->components->info(sprintf('%s: %d permissions', $context, count($names)));
        }

        return self::SUCCESS;
    }
}
