<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Tenant notification defaults (spec §17.4, §17.9)
|--------------------------------------------------------------------------
|
| Seeded into every tenant database (insert-only) at provisioning and on
| each defaults sync. Placeholders are written {{name}}; {{store_name}} is
| always available. Tenants customise the seeded rows, never this file.
|
*/

$n = static fn (array $audience, array $channels, string $subject, string $body, bool $mandatory = false): array => [
    'audience' => $audience,
    'channels' => $channels,
    'subject' => $subject,
    'body' => $body,
    'mandatory' => $mandatory,
];

$customer = ['email' => true, 'database' => true, 'push' => true];
$customerSms = ['email' => true, 'database' => true, 'sms' => true, 'push' => true];
$staff = ['email' => true, 'database' => true, 'push' => true];
$staffInbox = ['database' => true, 'push' => true];
$reserved = ['email' => true, 'database' => true];

return [
    // Customer-facing
    'customer.welcome' => $n(['customer'], ['email' => true],
        'Welcome to {{store_name}}',
        "Hello {{customer_name}},\n\nThank you for creating an account at {{store_name}}."),
    'customer.password_reset' => $n(['customer'], ['email' => true],
        'Reset your {{store_name}} password',
        "Hello {{customer_name}},\n\nUse this link to reset your password: {{reset_url}}\n\nThe link expires in {{expires_in_minutes}} minutes. If you did not ask for a reset, ignore this email.",
        true),
    'customer.email_verification' => $n(['customer'], ['email' => true],
        'Verify your email for {{store_name}}',
        "Hello {{customer_name}},\n\nConfirm your email address by opening this link: {{verification_url}}",
        true),
    'order.confirmed' => $n(['customer'], $customerSms,
        'Order {{order_number}} confirmed',
        "Hello {{customer_name}},\n\nThank you for your order {{order_number}} at {{store_name}}. Total: {{order_total}}.\n\nWe will let you know when it ships.",
        true),
    'order.payment_failed' => $n(['customer'], $customer,
        'Payment for order {{order_number}} failed',
        "Hello {{customer_name}},\n\nWe could not take payment for order {{order_number}}. You can try again from your order page: {{order_url}}"),
    'order.status_changed' => $n(['customer'], $customer,
        'Order {{order_number}} is now {{status}}',
        "Hello {{customer_name}},\n\nYour order {{order_number}} is now {{status}}."),
    'order.shipped' => $n(['customer'], $customerSms,
        'Order {{order_number}} has shipped',
        "Hello {{customer_name}},\n\nPart or all of your order {{order_number}} has shipped with {{carrier}}. Tracking number: {{tracking_number}}."),
    'order.out_for_delivery' => $n(['customer'], $customerSms,
        'Order {{order_number}} is out for delivery',
        "Hello {{customer_name}},\n\nYour order {{order_number}} is out for delivery today."),
    'order.delivered' => $n(['customer'], $customer,
        'Order {{order_number}} delivered',
        "Hello {{customer_name}},\n\nYour order {{order_number}} has been delivered. Thank you for shopping at {{store_name}}."),
    'order.cancelled' => $n(['customer'], $customer,
        'Order {{order_number}} cancelled',
        "Hello {{customer_name}},\n\nYour order {{order_number}} has been cancelled. Reason: {{reason}}."),
    'order.refunded' => $n(['customer'], $customer,
        'Refund for order {{order_number}}',
        "Hello {{customer_name}},\n\nWe refunded {{amount}} for order {{order_number}}. It may take a few days to appear on your statement."),
    'account.data_export_ready' => $n(['customer'], ['email' => true, 'database' => true],
        'Your data export is ready',
        "Hello {{customer_name}},\n\nThe copy of your personal data is ready. Download it here: {{download_url}}\n\nThe link expires on {{expires_at}}.",
        true),
    'return.requested' => $n(['customer'], $customer,
        'Return request {{return_number}} received',
        "Hello {{customer_name}},\n\nWe received your return request {{return_number}} for order {{order_number}}. We will review it shortly."),
    'return.approved' => $n(['customer'], $customer,
        'Return {{return_number}} approved',
        "Hello {{customer_name}},\n\nYour return {{return_number}} has been approved. {{instructions}}"),
    'return.rejected' => $n(['customer'], $customer,
        'Return {{return_number}} rejected',
        "Hello {{customer_name}},\n\nYour return {{return_number}} was not approved. Reason: {{reason}}"),
    'return.received' => $n(['customer'], $customer,
        'Return {{return_number}} received',
        "Hello {{customer_name}},\n\nWe received the items for return {{return_number}}."),
    'return.refunded' => $n(['customer'], $customer,
        'Return {{return_number}} refunded',
        "Hello {{customer_name}},\n\nWe refunded {{amount}} for return {{return_number}}."),
    'review.approved' => $n(['customer'], ['email' => true, 'database' => true],
        'Your review is live',
        "Hello {{customer_name}},\n\nYour review of {{product_name}} is now published. Thank you."),
    'question.answered' => $n(['customer'], ['email' => true, 'database' => true],
        'Your question about {{product_name}} was answered',
        "Hello {{customer_name}},\n\nYou asked: {{question}}\n\nAnswer: {{answer}}"),
    'gift_card.issued' => $n(['customer'], ['email' => true],
        'You received a {{store_name}} gift card',
        "Hello,\n\n{{sender_name}} sent you a gift card worth {{amount}}.\n\nCode: {{code}}\n\n{{message}}"),
    'sales_quotation.sent' => $n(['customer'], ['email' => true],
        'Quotation {{quotation_number}} from {{store_name}}',
        "Hello {{customer_name}},\n\nPlease find quotation {{quotation_number}} for {{total}}, valid until {{valid_until}}: {{quotation_url}}"),
    'product_subscription.payment_failed' => $n(['customer'], $customerSms,
        'Subscription payment failed',
        "Hello {{customer_name}},\n\nWe could not renew your subscription to {{product_name}}. Please update your payment method: {{account_url}}"),
    'back_in_stock.available' => $n(['customer'], $customer,
        '{{product_name}} is back in stock',
        "Hello,\n\n{{product_name}} is back in stock at {{store_name}}: {{product_url}}"),
    'repair_job.diagnosis_ready' => $n(['customer'], $customerSms,
        'Diagnosis ready for repair {{job_number}}',
        "Hello {{customer_name}},\n\nThe diagnosis for repair {{job_number}} is ready: {{diagnosis}}\n\nEstimated cost: {{estimated_cost}}."),
    'repair_job.ready_for_pickup' => $n(['customer'], $customerSms,
        'Repair {{job_number}} is ready for pickup',
        "Hello {{customer_name}},\n\nYour repair {{job_number}} is complete and ready for pickup."),
    'project.customer_update' => $n(['customer'], ['whatsapp' => true, 'email' => true],
        'Update on project {{project_name}}',
        "Hello {{customer_name}},\n\nProject {{project_name}} is now {{status}}."),
    'support.reply_received' => $n(['customer'], $customer,
        'New reply from {{store_name}} support',
        "Hello {{customer_name}},\n\nWe replied to your conversation:\n\n{{message_excerpt}}"),
    'coupon.expiring_soon' => $n(['customer'], $reserved,
        'Your coupon {{coupon_code}} expires soon',
        "Hello {{customer_name}},\n\nYour coupon {{coupon_code}} expires on {{expires_at}}."),
    'flash_sale.starting_soon' => $n(['customer'], $reserved,
        '{{sale_name}} starts soon',
        "Hello {{customer_name}},\n\n{{sale_name}} starts on {{starts_at}} at {{store_name}}."),
    'wishlist_item.back_in_stock' => $n(['customer'], $reserved,
        '{{product_name}} from your wishlist is back',
        "Hello {{customer_name}},\n\n{{product_name}} from your wishlist is back in stock: {{product_url}}"),
    'wishlist_item.price_drop' => $n(['customer'], $reserved,
        'Price drop on {{product_name}}',
        "Hello {{customer_name}},\n\n{{product_name}} from your wishlist is now {{price}}: {{product_url}}"),

    // Staff-facing
    'staff.password_reset' => $n(['admin'], ['email' => true],
        'Reset your {{store_name}} admin password',
        "Hello {{name}},\n\nUse this link to reset your password: {{reset_url}}\n\nThe link expires in {{expires_in_minutes}} minutes. If you did not ask for a reset, ignore this email.",
        true),
    'order.new_order_received' => $n(['admin'], $staff,
        'New order {{order_number}}',
        'A new order {{order_number}} for {{order_total}} was placed by {{customer_name}}.'),
    'contact.submission_received' => $n(['admin'], $staff,
        'New contact message from {{name}}',
        "{{name}} ({{email}}) wrote:\n\n{{message}}"),
    'staff.ownership_transferred' => $n(['admin'], ['email' => true, 'database' => true],
        'Store ownership transferred',
        'Ownership of {{store_name}} was transferred from {{previous_owner}} to {{new_owner}}.',
        true),
    'module.state_changed' => $n(['admin'], ['email' => true, 'database' => true],
        '{{module_name}} is now {{state}}',
        'The {{module_name}} module is now {{state}}. {{detail}}'),
    'order.payment_failed_staff_alert' => $n(['admin'], $staffInbox,
        'Payment failed for order {{order_number}}',
        'The payment for order {{order_number}} ({{order_total}}) failed: {{reason}}.'),
    'order.payment_needs_review' => $n(['admin'], $staff,
        'Payment for order {{order_number}} needs review',
        'The provider reported {{provider_amount}} for order {{order_number}}, which expected {{order_total}}. Review the payment before fulfilling the order.',
        true),
    'order.overpaid' => $n(['admin'], $staff,
        'Order {{order_number}} was overpaid',
        'Order {{order_number}} received {{net_paid}} against a total of {{order_total}}. Refund the difference or record it.'),
    'order.refund_needs_review' => $n(['admin'], $staff,
        'Refund for order {{order_number}} needs review',
        'The gateway did not confirm the refund of {{amount}} for order {{order_number}}. Check the provider dashboard.',
        true),
    'order.payment_disputed' => $n(['admin'], $staff,
        'Payment disputed on order {{order_number}}',
        'The customer disputed {{amount}} on order {{order_number}}. Respond before {{respond_by}}.',
        true),
    'promotion.limit_exceeded_offline' => $n(['admin'], $staffInbox,
        'Promotion {{promotion_name}} exceeded its limit',
        'An offline POS sale pushed promotion {{promotion_name}} past its usage limit.'),
    'inventory.stale_reservations' => $n(['admin'], $staffInbox,
        '{{count}} stale stock reservations',
        '{{count}} stock reservations on unconfirmed orders are older than 7 days. Review them to release stock.'),
    'export.ready' => $n(['admin'], ['email' => true, 'database' => true],
        'Your {{export_type}} export is ready',
        "Your {{export_type}} export is ready: {{download_url}}\n\nThe link expires on {{expires_at}}."),
    'tenant.custom_domain_verified' => $n(['admin'], ['email' => true, 'database' => true],
        '{{domain}} is live',
        'Your domain {{domain}} is verified and now serves your store over HTTPS.'),
    'payments.mode_changed' => $n(['admin'], ['email' => true, 'database' => true],
        'Payment mode changed to {{mode}}',
        '{{changed_by}} changed the store payment mode from {{previous_mode}} to {{mode}}.',
        true),
    'return.new_request' => $n(['admin'], $staff,
        'New return request {{return_number}}',
        '{{customer_name}} requested return {{return_number}} for order {{order_number}}.'),
    'review.pending_moderation' => $n(['admin'], $staffInbox,
        'Review awaiting moderation',
        'A new review of {{product_name}} awaits moderation.'),
    'question.pending_moderation' => $n(['admin'], $staffInbox,
        'Question awaiting moderation',
        'A new question about {{product_name}} awaits moderation.'),
    'inventory.low_stock' => $n(['admin'], $staff,
        'Low stock: {{product_name}}',
        '{{product_name}} ({{sku}}) has {{available}} left at {{warehouse_name}}.'),
    'inventory.out_of_stock' => $n(['admin'], $staff,
        'Out of stock: {{product_name}}',
        '{{product_name}} ({{sku}}) is out of stock at {{warehouse_name}}.'),
    'inventory.product_expiring_soon' => $n(['admin'], $staff,
        '{{count}} batches expiring soon',
        '{{count}} product batches expire within {{days}} days. Review them in inventory.'),
    'purchase_order.received' => $n(['admin'], $staffInbox,
        'Purchase order {{po_number}} received',
        'Stock for purchase order {{po_number}} from {{supplier_name}} has been received.'),
    'delivery.assignment_failed' => $n(['admin'], $staff,
        'Delivery failed for order {{order_number}}',
        'The delivery of order {{order_number}} by {{driver_name}} failed: {{reason}}.'),
    'pos.session_variance_flagged' => $n(['admin'], $staff,
        'Cash variance on register {{register_name}}',
        'Session {{session_id}} on {{register_name}} closed with a variance of {{variance}}.'),
    'accounting.posting_failed' => $n(['admin'], $staff,
        'Accounting posting failed',
        'An accounting entry for {{source}} could not be posted: {{reason}}.'),
    'hr.leave_request_submitted' => $n(['admin'], $staffInbox,
        'Leave request from {{employee_name}}',
        '{{employee_name}} requested {{leave_type}} leave from {{starts_on}} to {{ends_on}}.'),
    'hr.leave_request_approved' => $n(['admin'], $staff,
        'Your leave request was approved',
        'Your {{leave_type}} leave from {{starts_on}} to {{ends_on}} was approved.'),
    'hr.leave_request_rejected' => $n(['admin'], $staff,
        'Your leave request was rejected',
        'Your {{leave_type}} leave from {{starts_on}} to {{ends_on}} was rejected. Reason: {{reason}}'),
    'approval.step_pending' => $n(['admin'], $staff,
        'Approval needed: {{subject}}',
        '{{requester_name}} needs your approval for {{subject}}.'),
    'approval.request_approved' => $n(['admin'], $staff,
        'Approved: {{subject}}',
        'Your request {{subject}} was approved.'),
    'approval.request_rejected' => $n(['admin'], $staff,
        'Rejected: {{subject}}',
        'Your request {{subject}} was rejected. Reason: {{reason}}'),
    'project.assigned' => $n(['admin'], ['whatsapp' => true, 'database' => true],
        'You were assigned to {{project_name}}',
        'You were assigned to project {{project_name}}.'),
    'project_task.assigned' => $n(['admin'], ['whatsapp' => true, 'database' => true],
        'New task: {{task_title}}',
        'You were assigned the task {{task_title}} in {{project_name}}, due {{due_on}}.'),
    'support.message_received' => $n(['admin'], $staffInbox,
        'New support message from {{customer_name}}',
        "{{customer_name}} wrote:\n\n{{message_excerpt}}"),
    'seller.new_seller_application' => $n(['admin'], $staff,
        'New seller application: {{seller_name}}',
        '{{seller_name}} applied to sell on {{store_name}}.'),
    'seller.new_product_pending_approval' => $n(['admin'], $staffInbox,
        'Seller product awaiting approval',
        '{{seller_name}} submitted {{product_name}} for approval.'),
    'supplier.payment_due' => $n(['admin'], $reserved,
        'Supplier payment due: {{supplier_name}}',
        '{{amount}} is due to {{supplier_name}} on {{due_on}}.'),

    // Seller and supplier
    'seller.password_reset' => $n(['seller'], ['email' => true],
        'Reset your {{store_name}} seller password',
        "Hello {{name}},\n\nUse this link to reset your password: {{reset_url}}\n\nThe link expires in {{expires_in_minutes}} minutes. If you did not ask for a reset, ignore this email.",
        true),
    'seller.application_approved' => $n(['seller'], ['email' => true],
        'Your seller application is approved',
        "Hello {{seller_name}},\n\nWelcome to {{store_name}}. You can now sign in and list your products."),
    'seller.application_rejected' => $n(['seller'], ['email' => true],
        'Your seller application',
        "Hello {{seller_name}},\n\nWe are unable to accept your seller application. Reason: {{reason}}"),
    'seller.product_approved' => $n(['seller'], ['email' => true],
        '{{product_name}} is approved',
        "Hello {{seller_name}},\n\nYour product {{product_name}} is approved and visible in the store."),
    'seller.product_rejected' => $n(['seller'], ['email' => true],
        '{{product_name}} was not approved',
        "Hello {{seller_name}},\n\nYour product {{product_name}} was not approved: {{moderation_note}}"),
    'quotation_request.sent' => $n(['supplier'], ['email' => true],
        'Request for quotation {{request_number}} from {{store_name}}',
        "Hello {{supplier_name}},\n\n{{store_name}} requests a quotation for the items in request {{request_number}}, by {{respond_by}}: {{request_url}}"),
];
